# 学习 ndarray
## 1.ndarray特性
### 多维性

In [8]:
import numpy as np

In [ ]:
arr = np.array(5)   #创建一个0维数组
print(arr)
print("数组的维度为:", arr.ndim)     #查看数组的维度

5
数组的维度为: 0


In [13]:
arr = np.array([1,2,3])   #创建一个1维数组
print(arr)
print("数组的维度为:", arr.ndim)     #查看数组的维度

[1 2 3]
数组的维度为: 1


In [15]:
arr = np.array([[1,2,3],[4,5,6]])   #创建一个2维数组
print(arr)
print("数组的维度为:", arr.ndim)     #查看数组的维度

[[1 2 3]
 [4 5 6]]
数组的维度为: 2


### 同质性

In [ ]:
arr = np.array([1,'a'])     #将1转换成字符串，强制类型转换
print(arr)

['1' 'a']


In [ ]:
arr = np.array([1,1.5])     #将1转换成浮点数，强制类型转换
print(arr)

[1.  1.5]
