In [1]:
import numpy as np


# ndarray的创建方式

In [ ]:
# 原始创建方式

# 使用np.array()函数创建数组
list1 = [1,2,3]

# array()函数的参数
# dtype: 数组的元素类型，默认为float64
# copy: 是否复制数据，默认为True
# subok: 是否允许子数组，默认为True
# ndmin: 最小维度，默认为0
arr = np.array(list1,dtype=np.float64)
print(arr)
print("数组的维度为:", arr.ndim)     #查看数组的维度

print("-"*30)
# 使用np.copy()函数创建数组，深拷贝
# a=b这种方式是浅拷贝，修改原列表会修改所有引用的列表

ay = list([4,5,6])
arr2 = np.copy(ay)
arr3 = ay
print('修改原列表前')
print('arr2:',arr2)
print('arr3:',arr3)

print('修改原列表后')
ay[0] = 10
print('arr2:',arr2)
print('arr3:',arr3)
print('ay:',ay)



[1. 2. 3.]
数组的维度为: 1
------------------------------
修改原列表前
arr2: [4 5 6]
arr3: [4, 5, 6]
修改原列表后
arr2: [4 5 6]
arr3: [10, 5, 6]
ay: [10, 5, 6]


In [51]:
# 预定义形状的方式创建数组

a = np.zeros((2,3))
print(a)
b = np.ones((2,3))
print(b)
c = np.empty((2,3))
print(c)
d = np.full((2,3),100)
print(d)

print("-"*30)

arr = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
print(arr)
e = np.zeros_like(arr)
print(e)
f = np.ones_like(arr)
print(f)
g = np.empty_like(arr)
print(g)
h = np.full_like(arr,100)
print(h)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[100 100 100]
 [100 100 100]]
------------------------------
[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[100 100 100]
  [100 100 100]]

 [[100 100 100]
  [100 100 100]]]


In [60]:
# 使用np.arange()函数创建数组，等差数列
arr = np.arange(1,20,2)
print(arr)

# 使用np.linspace()函数创建数组,等间隔数列
arr1 = np.linspace(1,10,5)
print(arr1)

# 使用np.logspace()函数创建数组,等比数列,对数间隔数列
arr2 = np.logspace(1,10,10 , base=2)
print(arr2)

arr3 = np.logspace(5,10,6,base=3 , dtype=np.int64)
print(arr3)

print(3**5)
print(3**6)
print(3**7)
print(3**8)
print(3**9)
print(3**10)

[ 1  3  5  7  9 11 13 15 17 19]
[ 1.    3.25  5.5   7.75 10.  ]
[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]
[  243   729  2187  6561 19683 59049]
243
729
2187
6561
19683
59049


In [76]:
# 单位矩阵/类单位矩阵

arr = np.eye(3)
print(arr)

arr1 = np.eye(3,4,k=0)
print(arr1)

arr2 = np.eye(3,4,k=1)
print(arr2)

arr3 = np.eye(3,4,k=-1)
print(arr3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [78]:
# 对角矩阵 只有主对角线上的元素非零，其他元素为零
arr = np.diag([1,2,3])
print(arr)

arr1 = np.diag([5,1,2,3])
print(arr1)


[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [96]:
# 生成随机数组
# 生成0到1之间的随机浮点数(均匀分布)
arr = np.random.rand(3,4)
print(arr)


[[0.42674808 0.35491464 0.76675979 0.50143683]
 [0.1149523  0.94701844 0.19443707 0.50622405]
 [0.07643855 0.68476532 0.93048441 0.67779048]]


In [114]:
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(5,8,(3,4))
print(arr)


[[7.48363569 7.30368091 5.28489658 5.94575001]
 [6.22535358 7.63395423 5.39842991 6.87004765]
 [7.78373948 6.57778391 5.50113004 6.72850567]]


In [145]:
# 生成指定范围区间的随机整数
arr = np.random.randint(5,10,(3,4))
print(arr)


[[6 6 5 9]
 [5 8 8 9]
 [6 6 5 9]]


In [192]:
# 生成随机数列（正态分布）（均值0）(-3到3之间)
arr = np.random.randn(1,2)
print(arr)


[[0.37907061 2.0082456 ]]


In [200]:
# 设置随机种子
np.random.seed(100)
arr = np.random.randint(5,10,(3,4))
print(arr)


[[5 5 8 5]
 [7 9 7 7]
 [7 7 6 5]]
