# 索引和切片

In [2]:
import numpy as np

In [5]:
arr = np.random.randint(1,1000,20)
print(arr)


print(arr[10])
print(arr[:])   # 打印数组的所有元素
print(arr[10:20])   # 打印数组的第11个元素到第20个元素 左闭右开
print(arr[::2])   # 打印数组的所有偶数索引元素
print(arr[slice(10,20,2)])   # 打印数组的第11个元素到第20个元素 左闭右开，步长为2
print(arr[(arr > 200) & (arr < 500)])   # 布尔索引


[262  15 456 501 485 605 372 994 675 946 785 696 749  67 928 923 450 335
 628  43]
785
[262  15 456 501 485 605 372 994 675 946 785 696 749  67 928 923 450 335
 628  43]
[785 696 749  67 928 923 450 335 628  43]
[262 456 485 372 675 785 749 928 450 628]
[785 749 928 450 628]
[262 456 485 372 450 335]


In [ ]:
# 二位数组的索引和切片
arr = np.random.randint(500,1000,(4,5))

print(arr)

print(arr[2,3]) # 打印数组的第3行第4列的元素
print(arr[1, :])    # 打印数组的第2行的所有元素
print(arr[:, 2])    # 打印数组的第3列的所有元素
print(arr[2][ arr[2] > 700])     # 打印数组的第3行大于700的元素
print(arr[:,2][ arr[:,2] > 700])     # 打印数组的第3列大于700的元素 


[[737 903 516 755 841]
 [686 796 643 704 513]
 [999 703 846 538 578]
 [800 848 785 719 992]]
538
[686 796 643 704 513]
[516 643 846 785]
[999 703 846]
[846 785]
