# ndarray的运算

In [1]:
import numpy as np

In [4]:
# 数组的加法
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(a1 + a2)
print(a1 - a2)
print(a1 * a2)
print(a1 / a2)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
# python原生的加法
a1 = [1,2,3]
a2 = [4,5,6]
a3 = []
for i in range(len(a1)):
    a3.append(a1[i] + a2[i])
print(a3)

# 原生的加法是拼接操作，没有减法、乘法、除法
print(a1 + a2)

[5, 7, 9]
[1, 2, 3, 4, 5, 6]


In [ ]:
# 二维数组的运算    ，注意这不是矩阵的乘除法
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[7,8,9],[10,11,12]])
print(a1 + a2)
print(a1 - a2)
print(a1 * a2)
print(a1 / a2)


[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [7]:
# 矩阵和标量的运算
a1 = np.array([[1,2,3],[4,5,6]])
print(a1 + 10)
print(a1 - 10)
print(a1 * 10)
print(a1 / 10)

[[11 12 13]
 [14 15 16]]
[[-9 -8 -7]
 [-6 -5 -4]]
[[10 20 30]
 [40 50 60]]
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]]


In [ ]:
# 广播机制
a = np.array([[1],[2],[3]])
b = np.array([4,5,6])

'''
    1 2 3

    4
    5
    6
 
    1 2 3
    1 2 3
    1 2 3   

    4 4 4
    5 5 5
    6 6 6

'''

print(a + b)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [14]:
# 矩阵的乘法运算
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[4,5,6],[3,2,1]])
print(a @ b.T)

[[32 10]
 [77 28]]
