# 基础数学函数

In [2]:
import numpy as np

In [ ]:
# 平方根运算    返回浮点数
print(np.sqrt(9))

print(np.sqrt([9,16,25]))

3.0
[3. 4. 5.]


In [ ]:
# 计算指数  以e为底数，指数为1的值  e^x
print(np.exp(1))

print(np.exp(2))

2.718281828459045
7.38905609893065


In [ ]:
# 计算自然对数  以e为底数，指数为1的值  lnx
print(np.log(1))

print(np.log(np.e))
print(np.log(2))
print(np.log(3))

0.0
1.0
0.6931471805599453
1.0986122886681098


In [14]:
# 计算三角函数
print(np.sin(np.pi/2))
print(np.cos(-np.pi))
print(np.tan(np.pi/4))


1.0
-1.0
0.9999999999999999


In [15]:
# 计算绝对值
print(np.abs(-10))
print(np.abs(10))

10
10


In [18]:
# 计算a的b次方
print(np.power(2,3))
print(np.power(3,2))
print(np.power(5,2))
print(np.power(np.e,2))

8
9
25
7.3890560989306495


In [22]:
# 四舍五入
print(np.round([2.3,3.7,4.1,5.5,4.5,4.50000000000001]))


[2. 4. 4. 6. 4. 5.]


In [23]:
# 向上取整，向下取整
print(np.ceil([2.3,3.7,4.1,5.5,4.5]))
print(np.floor([2.3,3.7,4.1,5.5,4.5]))

[3. 4. 5. 6. 5.]
[2. 3. 4. 5. 4.]


In [ ]:
# 检测缺失值    检测nan值
print(np.isnan([1,2,3,np.nan,4]))

[False False False  True False]


# 基础统计函数
## 统计函数
### 求和，计算平均值，计算中位数，计算标准差，计算方差
### 计算最大值，计算最小值
### 计算分位数，计算累计和，计算累积差

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,20,8)
print(arr)


[15 16  3  9 15 18 18 10]


In [8]:
# 求和
print(np.sum(arr))

104


In [7]:
# 计算平均值
print(np.mean(arr))

13.0


In [9]:
# 计算中位数
print(np.median(arr))

15.0


In [ ]:
# 计算标准差，方差
# 先求数据均值，再计算每个数据与均值的差的平方和，总体方差除以数据总数、样本方差除以样本容量减一得到方差，方差开平方即得标准差。
# 描述的是数据的离散程度
print(np.var(arr))
print(np.std(arr))

24.0
4.898979485566356


In [ ]:
# 最大值和最小值
print(np.max(arr))
print(np.min(arr))

# 最大值和最小值的索引
print(np.argmax(arr))
print(np.argmin(arr))



18
3
5
2


In [11]:
np.random.seed(0)
arr = np.random.randint(0,100,4)
print(arr)

# 分位数
# 中位数
print(np.median(arr))

# 50%分位数
print(np.percentile(arr,50))

print(np.percentile(arr,25))

[44 47 64 67]
55.5
55.5
46.25


In [12]:
# 累积和与累积积
print(np.cumsum(arr))
print(np.cumprod(arr))


[ 44  91 155 222]
[     44    2068  132352 8867584]


# 基础比较函数

In [13]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])
print(np.greater(arr,3))    # 大于3

print(np.less(arr,3))    # 小于3

print(np.equal(arr,3))    # 等于3

print(np.equal([1,2,3],[3,2,3]))    # 两个数组形状相同，对应元素是否相等

print(np.not_equal(arr,3))    # 不等于3

[False False False  True  True]
[ True  True False False False]
[False False  True False False]
[False  True  True]
[ True  True False  True  True]


In [39]:
# 逻辑与    全真为真
print(np.logical_and([1,2],[0,2]))    # 对应元素进行逻辑与操作，返回结果为布尔值

# 逻辑或    全假为假
print(np.logical_or([1,0],[0,0]))    # 对应元素进行逻辑或操作，返回结果为布尔值

# 逻辑非    取反
print(np.logical_not([1,0]))    # 对应元素进行逻辑非操作，返回结果为布尔值

# 只要有一个为真，就返回真
print(np.any([1,0,0,0,0]))   
print(np.any([0,0,0,0,0])) 

# 全部是真，才返回真
print(np.all([1,1,1,1,1]))   
print(np.all([0,1,1,1,1])) 

# 自定义条件
print("-"*30)
print(arr)
print(np.where(arr>3,500,404))    # 对应元素进行判断.如果大于3，就返回500，否则返回404

print(np.select([arr>3,arr<=3],[500,404]))    # 对应元素进行判断.如果大于3，就返回500，否则返回404

[False  True]
[ True False]
[False  True]
True
False
True
False
------------------------------
[1 2 3 4 5]
[404 404 404 500 500]
[404 404 404 500 500]


# 基础排序函数

In [2]:
import numpy as np

In [9]:
arr = np.array([4,3,2,3,4,5,5,6,7,8,9])

a1 = arr.copy()
print(a1)

a2 = arr.copy()
print(a2)
print('-'*20)

a1.sort()   # 会改变原数组
print(a1)

print(np.sort(a2))   # 不会改变原数组
print(a2)
print('排序后的索引:',np.argsort(a2))   # 返回排序后的索引


[4 3 2 3 4 5 5 6 7 8 9]
[4 3 2 3 4 5 5 6 7 8 9]
--------------------
[2 3 3 4 4 5 5 6 7 8 9]
[2 3 3 4 4 5 5 6 7 8 9]
[4 3 2 3 4 5 5 6 7 8 9]
排序后的索引: [ 2  1  3  0  4  5  6  7  8  9 10]


In [ ]:
# 去重函数
arr = np.array([4,3,2,3,4,5,5,6,7,8,9])

print(np.unique(arr))

[2 3 4 5 6 7 8 9]


In [ ]:
# 数组的拼接
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.concatenate((arr1,arr2)))
print(np.concatenate((arr1,arr2),axis=0))

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
# 数组的分割
arr = np.array([3,4,5,6,7,8,4,2,1,3,4,4,5,6,7,8,9,0])

print(np.split(arr,2))  # 数组的元素个数必须被2整除，否则会报错

print(np.split(arr,[2,5,6]))


[array([3, 4, 5, 6, 7, 8, 4, 2, 1]), array([3, 4, 4, 5, 6, 7, 8, 9, 0])]
[array([3, 4]), array([5, 6, 7]), array([8]), array([4, 2, 1, 3, 4, 4, 5, 6, 7, 8, 9, 0])]


In [ ]:
# 重新数组的形状
arr = np.array([1,2,3,4,5,6,7,8,9,0])

print(arr)
print(arr.reshape(2,5)) # 重新数组的形状，必须与原数组的元素个数相同，否则会报错

print(arr.reshape(5,2))

[1 2 3 4 5 6 7 8 9 0]
[[1 2 3 4 5]
 [6 7 8 9 0]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]
